# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# Find more information at:
# https://github.com/microsoft/msvc-code-analysis-action

name: Microsoft C++ Code Analysis

on: [push]
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#  schedule:
#    - cron: '43 4 * * 6'

env:
  build: '${{ github.workspace }}/build'
  WXVERSION: 3.2.2.1
  WXBUILDVER: 3.2.2.1_0

permissions:
  contents: read

jobs:
  analyze:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Analyze
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: wxWidgets
        run: |
             # If there's no installation of wxWidgets available, we have to build it
             Start-FileDownload "https://github.com/wxWidgets/wxWidgets/releases/download/v${env:WXVERSION}/wxWidgets-${env:WXVERSION}.7z"
             echo '* Unpacking wxWidgets sources'
             7z x "wxWidgets-${env:WXVERSION}.7z" "-oC:\wxwidgets-source_${env:WXVERSION}" -y
             echo '* Building wxWidgets from sources'
             mkdir "C:\wxwidgets-build_${env:WXBUILDVER}" | Out-Null
             pushd "C:\wxwidgets-build_${env:WXBUILDVER}"
             cmake -G "Visual Studio 17 2022"  -DCMAKE_BUILD_TYPE=Release -DwxBUILD_SHARED=NO -DwxUSE_STC=NO -DwxUSE_RIBBON=NO "-DCMAKE_INSTALL_PREFIX="C:\wxwidgets-install_${env:WXBUILDVER}" -Wno-dev "C:\wxwidgets-source_${env:WXVERSION}"
             cmake --build .
             cmake --install .
             popd
      - name: Configure CMake
        run: cmake -B ${{ env.build }}
      # Build is not required unless generated source files are used
      # - name: Build CMake
      #   run: cmake --build ${{ env.build }}
      - name: Initialize MSVC Code Analysis
        uses: microsoft/msvc-code-analysis-action@04825f6d9e00f87422d6bf04e1a38b1f3ed60d99
        # Provide a unique ID to access the sarif output path
        id: run-analysis
        with:
          cmakeBuildDirectory: ${{ env.build }}
          # Ruleset file that will determine what checks will be run
          ruleset: NativeRecommendedRules.ruleset
      # Upload SARIF file to GitHub Code Scanning Alerts
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}
      # Upload SARIF file as an Artifact to download and view
      # - name: Upload SARIF as an Artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: sarif-file
      #     path: ${{ steps.run-analysis.outputs.sarif }}
